dist: xenial
sudo: required
language: python
python:
- '3.5'
- '3.6'
before_install:
- sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get -y update
- sudo apt-get install -y gdal-bin python-tk libopenjpeg-dev libgdal-dev
- pip install numpy cython
- 'pip install fiona rasterio netcdf4 --no-binary :all:'
- if [ $MAPCHETE_VERSION == "master" ]; then pip install git+https://github.com/ungarj/mapchete.git@master#egg=mapchete;
  else pip install mapchete==$MAPCHETE_VERSION --no-binary :all:; fi;
- export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
install:
- pip install -e .
- pip install pytest coveralls
script:
- coverage run --source=mapchete_xarray setup.py test
after_success:
- coveralls
env:
  matrix:
  - MAPCHETE_VERSION="master"
  global:
  - secure: qv3B/Ww/B7Z/z53J8N+5jGc14ae7vXeLs+uQvKpabhweNni+sc6CfugNEhmLUKsLZX4wRXCvnhAVIh6v98gA1FAUdx7bZHApsHi2NyYNwHmzExe+eoucauq+o9joreMQrwhKB93S97uORT+TMJEkr3coz1I43T22wj0Wv5AcipwWyLb+Co0GA9oZTrIb9zgtRnN655EZxbQZe3td+NrzK/Yr12OIzVOh25TkoSFKw0YygAzLA5zw0UcmIPeigLGOGBznAKZh916xEpUUEzIY9hqAWffjYZjUsx3jBno2qQLO0hCZZYwluRodMHi4PnxLd3DHY0dwnO2wjsN2esf1m/Au7HI5EL9S1qxQP08jLXL9hRdqDx+1XhcdKiXaEUCNOWtOLZmxpat6b6Xw6hb0fc+et/NtdxH7iD2ftyV+5OmH3oHwcA44mc32EQljlHYwkVMdhjNYnDnE+a8WzMn88ZCH5ZIWBCWRwSEQQzK8IgPHNlocPH9FVJf54DYMTi+Y61YWiD/VkeZvWAaR+Yc+F9dFpgzOTqTx9wf8wpTP9sygWvw/o/0PIoAYguw8TuucHQTprX5qJSo/zGWkh8Aj+6V78FWnMwhCHGS1RRDRdrG9JrpG4gWsYUEMAU8A2TOcKUomTstLXS6tVxTuBKWSWfPTIfx44ALmCWVotAS6n7s=
  - secure: QO0i87Uqk2BWVR+pPp58E8Kvqgs19eQ3S5tvhsTJDVEQA2EHhmblb+OhT4LO/IHbefUldqUISy98+zkBTj2SyIkh+moIwXnLxggm3JxzmHBJzti+OB5pKkkHq5Dkz1D4Xzf4pY9D0Cb0I+HPfIbtZWRLACIo2qL6qSZ/1bda6q9wAXoAPuHvotdDVOY1+8996PuXUGZFhhcJoQoG/r+0U/LNkMUpMJGk5wmyoGpIG3Tudc0OcC+RgibqgDytQotQ4Q/jPJtmEzL9QGEFKC6euHvl8qNL/cjKLyO1TN6c2XDwhFpq6n6hR1B63QeK3/Aq00BQjy8CsA2Q+mRhA7F2PD5AiLUuH+vTeQ83K8tdMTbbYUALAwgzjptskXi0sNql1PtZK3vUuZ5w8Bot083aVOaOL+NbfipYUFsNMJHeHrJ2aRkNR2MpeSv/16t2IebgrUwUDDfqGocjQ9+XtBRAql7V2shpJ4Bks/wqP3dXxAV3JiwIrll71oKtNU5giEnOVJC473wJAz/1lSSH2IeOGVaH6oF+BwP9x8KNL4VGPtmlYHLgjTV0UlPUHIZuCsnjahxRmi/Hah/ga9BnIbR6h6fI4vv4QNNxRZDOpFH4yaNCdr4tG1Z2Zz3Xz6w8Ljen1J9IOCIiNHH6FJZaW1MFogoOclZZ+Nl8mHL9I7zmI+A=
